import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

const links = [
  { href: "/", label: "home" },
  { href: "/todos", label: "todos" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className=" bg-blue-500">
            <ul className="flex gap-4 py-4  wrapper ">
              {links.map((link) => (
                <li key={link.href}>
                  <Link
                    className=" capitalize text-white font-bold text-2xl"
                    href={link.href}
                  >
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
